Dockerfile

The intend of this PR is to decrease the docker image size by using a multi-stage build approach.
This eliminates the need to have development packages in the final image.
Additional deletion of `*.pyc` files and `__pycache__` dirs in the Python install layer within the final image save another 20 MBytes.
```bash
REPOSITORY       TAG     IMAGE ID      CREATED         SIZE
pwncat-single    latest  0d79acd717c9  8 minutes ago   415MB    # <-- before this PR
pwncat-multi     latest  0ce4b614686c  9 seconds ago   165MB    # <-- with this PR
```
I went ahead and tested this locally to the best of my knowledge.
The only thing I am currently not sure of is if the **`openssl`** package is required in the final build or not.
It might be for the SSH functionality, but I was not able to figure out …

Use multi-stage build for the docker image to reduce size

---

pwncat/commands/escalate.py
pwncat/data/gtfobins.json
pwncat/gtfobins.py
pwncat/modules/linux/enumerate/creds/password.py
pwncat/modules/linux/enumerate/escalate/leak_privkey.py
pwncat/modules/linux/enumerate/software/sudo/cve_2019_14287.py
pwncat/platform/linux.py

This pull request is for issue #98. The root of this problem was a
typo: missing square braces around enumeration. However, it
also shouldn't have been raising a module failed error in that case.
After fixing that problem, I found a few more bugs while testing
with Metasploitable2, so I fixed those:
- Added small sleeps in escalation to let the shell keep up
- stat behaves oddly, so added a loop to retry on parsing failure
- Fixed the **syntax** of the mtr gtfobins payload
- Fixed the nmap gtfobins payload
The mtr gtfobins payload is still not right, as it is unable to
read files as it should, but I'll work on that moving forward.
For now, there are no exceptions and escalation is working properly
through `nmap`.

Fixed sudo version enumeration

---

pwncat/__main__.py
pwncat/channel/ssh.py
pwncat/commands/connect.py

The `://` suffix wasn't being removed from the protocol and the host was being parsed as an empty string instead of `None` when it wasn't specified. This should fix #107. @cyal1 if you've got the time/attention, I'd appreciate you giving this branch a try and letting me know if this fixes your issue before I merge. Thanks for reporting!

Fix protocol parsing

---

pwncat/platform/windows.py
test.py

I've updated the C2 library, and this branch points to the newest C2 version. This should fix #110. This branch also contains a fix for the `Windows.abspath` method which used to raise a FileNotFoundError for non-existent files. It now correctly resolves relative paths for non-existent files.
@3m0W33D, If you have a few minutes to pull this branch down, I'd appreciate you giving it a try to make sure it solves the issue you were seeing.

Updated C2 version and Windows.abspath

---

.github/workflows/publish.yml
README.md
docs/source/configuration.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/windows.rst
pwncat/__main__.py
pwncat/commands/run.py
pwncat/config.py
pwncat/db.py
pwncat/facts/windows.py
pwncat/manager.py
pwncat/modules/__init__.py
pwncat/modules/windows/enumerate/user/__init__.py
pwncat/platform/__init__.py
pwncat/platform/windows.py
test.py

This branch adds support for the latest release of `pwncat-windows-c2` to support third-party .Net plugins for the Windows Platform.
- Updated documentation for Plugin API
- Updated README with notes on Windows support
- Added plugin API to Windows C2
- Added GitHub Action to package Windows plugins and attach to releases automatically.
- Added early support for BadPotato supported by [pwncat-badpotato](https://github.com/calebstewart/pwncat-badpotato) plugin (step toward #106)

Feature: Reflective .Net Plugins

---

pwncat/commands/upload.py
pwncat/data/gtfobins.json
pwncat/platform/linux.py

The old logic for exiting the process when writing to a file was flawed. I also increased the block size for `dd` to ensure it reads data as quickly as possible while we upload.
This should fix #117. @3m0W33D if you could give this branch a try and let me know. It worked for me (on Wekor) as seen in the below screenshot. Thanks for reporting!

Modified File Close Routine

---

pwncat/platform/linux.py

I'm not sure why this would happen, but it should fix #116. I just added a check in the setup to see if `SHELL` pointed to `nologin` and attempted to correct it. I tested locally by forcing that environment setup, and it appears to work fine.

Checked for SHELL pointing to nologin

---

pwncat/modules/linux/enumerate/system/network.py
pwncat/platform/linux.py

The zsh shell uses a different syntax for colored prompts. As such, I've
divided the prompt setup into three different options based on the
basename of the active shell: `sh` (uncolored), `zsh` and `default`.
Other shells can be added to `Linux.PROMPTS` as needed in the future.
Also, add the `-c=never` flag to the `ip` command in `enumerate.system.network`
so that color codes aren't output by the command.
Fixes #126.

Add Support for Multiple Shell Types and Removed Colors from `ip` output

---

pwncat/commands/sessions.py
pwncat/platform/linux.py

The current value for setting `PS1` variable for `zsh` isn't working. It is not showing any colors in my case.
This fixes a part of Issue https://github.com/calebstewart/pwncat/issues/126
Moreover, the following image shows the `upgrading from sh to /usr/bin/bash` message as well
Please note the `$SHELL` value
<hr>
There is another issue within `pwncat/commands/sessions.py`.
Trying to kill an invalid session throws an error showing the _traceback_
> NOTE: we do not need a session for this error to pop up

A few minor fixes

---

pwncat/channel/__init__.py
pwncat/channel/socket.py
pwncat/modules/linux/enumerate/system/container.py
pwncat/platform/linux.py

The `ChannelFile` implementation raised a BlockingIOError in certain
circumstances which is against the documented implementation for a
subclass of `RawIOBase`. This was causing odd behaviour like occasional
missing command output (e.g. empty environment variables)
Also, changed the shell detection to prioritize using `readlink -f /proc/$$/exe`
and alternatively fall back to `SHELL` if needed since shells aren't consistent
on whether this variable is set upon starting the shell.
This *should* once again fix #126. Hopefully. :sob:

Identified critical error in RawIOBase implementation

---

CHANGELOG.md
Dockerfile

Fixes #134.
This pull request updates the Dockerfile to pin the base image to Alpine v3.13.5, and also install pwncat within a virtual environment inside the container. DockerHub was showing a Permission Denied error when building for an unknown reason. Doing these two things appears to have fixed this. I added a test tag to the automatic builds for this branch, and the build succeeded.
- Pinned Alpine to 3.13.5 in Dockerfile
- Installed pwncat within a virtual environment at /opt/pwncat inside the container

[FIX #134] Pin Alpine to 3.13.5 to fix DockerHub automatic builds

---

CHANGELOG.md
docs/source/installation.rst
docs/source/usage.rst
pwncat/__main__.py
pwncat/channel/__init__.py
pwncat/channel/bind.py
pwncat/channel/connect.py
pwncat/channel/socket.py
pwncat/channel/ssh.py
pwncat/channel/ssl_bind.py
pwncat/channel/ssl_connect.py
pwncat/commands/connect.py
test.py

Fixes #118.
This pull requests adds two new channel classes/protocols: `ssl-bind` and `ssl-connect`. As with their unencrypted counterparts, these channels connect to or listen for a direct connection from/to the victim over a socket. After receiving or establishing a connection, the channel wraps the socket in an SSL context, and proceeds identically to the basic `bind` and `connect` channels.
The `ssl-bind` protocol requires two extra arguments: `certfile` and `keyfile`. At some point, I may implement automatic self-signed cert/key generation, but currently they must be generated separately and specified. To facilitate these new protocol options, a new argument was added to the entrypoint and the `connect` command. This argument is named `certificate` (or `cert` for short) and must …

[FEATURE #118] Encrypted Bind and Reverse Shells 

---

CHANGELOG.md
pwncat/commands/upload.py
pwncat/platform/linux.py
pwncat/util.py
tests/test_fileio.py
tests/test_platform.py

Fixes #140.
With these changes, when exiting a file write process, we send 2 EOFs if that last sent character was a new line and 4 if the last sent character was not a new line. This is counter-intuitive, but from all my testing, this appears to work consistently. I've added test cases for large and small files with both binary data and printable/text data and all tests pass as well as tests with the original TryHackMe machine which the issue was reported for.
It appears that you need to send every C-d twice, but I can't figure out why. All manual testing only requires a single C-d, but double each seems to correctly behave with automated file IO. If someone can explain this, I'd be very interested, but I cannot figure it out. In any case, this seems to work with the pwncat-testing docker …

[FIX #140] Remove C-d Loop in LinuxWriter Close Routine

---

CHANGELOG.md
pwncat/platform/windows.py

The `readline` import was accidentally removed during `flake8` cleanup. This broke the remote shell for Windows targets. I've added it back with a `noqa: F401` tag to appease flake8.
- Re-added readline import to windows platform

Re-added readline import after regression

---

CHANGELOG.md
pwncat/channel/socket.py
pwncat/commands/back.py
pwncat/commands/connect.py
pwncat/manager.py
pwncat/modules/linux/enumerate/user/group.py
pwncat/platform/__init__.py
pwncat/platform/linux.py
pwncat/platform/windows.py
setup.py

Fixes #133.
Added better exception handling in `Manager.interactive` which should now withstand dropped sessions. 
- Improved exception handling in across the framework.

[FIX #133] Various exception handler fixes for stability

---

CHANGELOG.md
pwncat/channel/socket.py
pwncat/manager.py
pwncat/modules/agnostic/enumerate/gather.py
pwncat/modules/enumerate.py
pwncat/modules/windows/enumerate/system/processes.py
pwncat/platform/windows.py

Created a new enumeration module which allows enumerations to be scoped to either the host (i.e. the victim/target) or to the active session. When enumerations are scoped to the session, the results/facts are only saved to the session. Other sessions do not share the results, and they will be lost after closing the session.
This is useful for things like process privileges or user tokens on Windows which are only valid in the context of the current session.
- Added `SCOPE` variable to base enumeration module class
- Added `Scope` enum defining `SESSION`, `HOST`, and `NONE` scopes

Added enumeration scopes

---

.gitattributes

No major changes here. Added a `.gitattributes` file which should remove the powershell language statistics from the project on Github. For reference, I got the info for how to do this from [here](https://github.com/github/linguist/blob/master/docs/overrides.md).

added gitattributes to hide powershell from language statistics

---

CHANGELOG.md
pwncat/facts/windows.py
pwncat/modules/agnostic/enumerate/escalate/replace.py
pwncat/modules/enumerate.py
pwncat/modules/windows/enumerate/token/potato.py
pwncat/modules/windows/enumerate/token/privs.py
tests/test_fileio.py

Fixes #106.
Added an execute ability named `UserToken` under `pwncat.facts.windows`. This execute ability will utilize a leaked user token to impersonate the identity of another user. The `enumerate.token.potato` module implements the [BadPotato](https://github.com/BeichenDream/BadPotato) technique to leak a SYSTEM token. This can then be used to impersonate the system account. These two pieces allow pwncat's `escalate` command to effectively escalate to the `NT AUTHORITY\SYSTEM` account.
- Added `enumerate.token.potato` and `enumerate.token.privileges` modules
- Added `UserToken` standard Windows fact type for other token leaking situations in the future.

[FEATURE #106] Token Impersonation Ability and BadPotato PoC

---

CHANGELOG.md
docs/source/api/pwncat.facts.escalate.rst
docs/source/api/pwncat.facts.rst
docs/source/commands/index.rst
docs/source/commands/listen.rst
docs/source/commands/listeners.rst
pwncat/commands/__init__.py
pwncat/commands/listener_new.py
pwncat/commands/listeners.py
pwncat/manager.py
pwncat/platform/windows.py
test.py

Fixes #43.
The following are some design goals I have:
I have the above working now, and with some more testing, I'll move this from a draft state to ready for review.
The `Manager` class now has a method named `create_listener`. A listener is a thread which maintains a raw socket listener (optionally wrapped in an SSL context). When a new connection is received, it uses the protocol specified during creation to construct a pwncat `Channel`. This must be a protocol which accepts a single `client` argument which is an open socket. Currently, the only protocol that supports this is `socket`. 
Once the channel is established, the listener will check if a platform was assigned at creation. If it was, a full session is established using the specified platform and the new channel, and the …

[FEATURE #43] Background Listeners

---

CHANGELOG.md
pwncat/__main__.py
pwncat/channel/__init__.py
pwncat/channel/connect.py
pwncat/commands/__init__.py
pwncat/commands/connect.py
pwncat/manager.py
pwncat/platform/linux.py
pwncat/platform/windows.py
pwncat/subprocess.py

Fixes #156
There was a `flake8` warning about an unused import, see https://github.com/Mitul16/pwncat/commit/a4cee5be27427d528b8a3e849f83c020dae6945b
Sorry for closing my last __PR__, there was one incorrect commit and some redundant commits added later.
I wanted to keep it all clean :sweat_smile: 
There is just _one difference_ in this __PR__, see https://github.com/Mitul16/pwncat/commit/b511a37f71e7c8f722b70ab3d030d7c70d7f8c7d
I have changed the error messages in `pwncat/channel/connect.py` so that they show the correct message.
- Fixed a possible exception due to _pre-registering_ of `session` with `manager`
- Added alternatives to `bash` to be used during _shell upgrade_ for a _better shell_
- Added a warning message when a `KeyboardInterrupt` is caught
- Changed some 'red' warning …

[FIXED #156] Raised exception on using 'sessions'

---

CHANGELOG.md
pwncat/__main__.py
pwncat/commands/connect.py

When processing the connection string for the `connect` command and the entrypoint, the `:` was not stripped from a password. This branch correctly strings the leading colon when a password is passed like: `ssh://user:password@host`.
- Corrected password processing in connection string

Correct password processing in connection string

---

CHANGELOG.md
pwncat/channel/socket.py

The `Socket` channel type did not handle the results of `socket.getpeername` for IPv6 sockets. These updates fix this, and also normalize the hostname for targets that result in either `::1` or `127.0.0.1` to simply `localhost`. This is mostly cosmetic, but I think it reads nicer in the pwncat output and seemed relatively relevant to this fix.
Fixes #159.
- Ignored extra data in result from `socket.getpeername` when using IPv6
- Translated both `::1` and `127.0.0.1` to the hostname `localhost` for clearer output

[FIXES 159] Correctly handle IPv6 Sockets

---

CHANGELOG.md
pwncat/gtfobins.py
pwncat/platform/linux.py

Fixes #183. There was a fallthrough case not handled in the sudo rule parsing related to wildcard characters in the sudo rules. I corrected this deficiency, and the enumeration seems to be working on the reported target in issue #183.
- Covered edge case in sudo rule parsing for wildcards ([#183](https://github.com/calebstewart/pwncat/issue/183))
- Added fallthrough cases for PTY methods in case of misbehaving binaries (looking at you: `screen`)

Fixed sudo rule parsing

---

.dockerignore
CHANGELOG.md
Dockerfile

Fixes #169. I updated the docker file to depend on the `python3.9-alpine` image to fix Python version mismatches as detailed in that issue. I'm preferring this over the fix in #171 as discussed there. Basically, we used to depend on `alpine` directly and install python manually. That was problematic. This should be more consistent.
- Changed docker base image to `python3.9-alpine`

[FIX #169] Update docker base image

---

CHANGELOG.md
pwncat/modules/linux/enumerate/escalate/leak_privkey.py
pwncat/platform/linux.py

Fixes #181. This fix will make the `enumerate.escalate.leak_privkey` module leak keys for all users when we detect a file-read ability for `UID=0`. 
I have also added an exception to the `LinuxReader` and `LinuxWriter` classes. If the underlying process exits with a non-zero exit code, the close method will raise a `PermissionError`. In *most* cases, this is the correct behavior. In cases where we *can* check before hand, we do. In the case of privilege escalation, we often can't test the permissions of the files we are attempting to access, and therefore defaulting to a `PermissionError` seems logical.
- Leak private keys for all users w/ file-read ability as UID=0 ([#181](https://github.com/calebstewart/pwncat/issues/181))
- Raise `PermissionError` when underlying processes terminate …

Updated leak_privkey to leak all keys when UID=0

---

CHANGELOG.md
pwncat/channel/ssh.py

Change the SSH channel implementation to call the correct paramiko method for loading a file path vs a file-like object when using an encrypted private key.
Fixes #185 
- Added logic for calling correct paramiko method when reloading an encrypted SSH private key

[FIXES 185] Added logic for calling correct paramiko method

---

CHANGELOG.md
pwncat/modules/linux/enumerate/file/suid.py
pwncat/modules/linux/enumerate/software/sudo/cve_2019_14287.py
pwncat/modules/linux/enumerate/software/sudo/rules.py
pwncat/platform/linux.py

This pull request makes pwncat use only `Stream.RAW` gtfobins payloads for Linux platforms. This ensures that we don't pick up any remaining `base64` streams and also don't accidentally use a `Stream.PRINT` stream when writing/reading binary data.
This pull request only fixes small part of #195, but does not rectify the entire issue. A larger effort will be needed to close that issue.
- Forced `Stream.RAW` for GTFObins interactions

Forced Stream.RAW for gtfobins interactions

---

CHANGELOG.md
pwncat/platform/linux.py

Added a custom `_do_custom_which` method to the `Linux` platform. During initialization, if a local implementation of `which` is not found, pwncat will default to using this custom which implementation, which looks roughly like:
```
/bin/bash -c 'IFS='"':'"'; for path in $PATH; do if [ -f "$path/$binary_name" ]; then echo "$path/$binary_name"; fi; done; IFS='"' '"
```
Fixes #193.
- Added Linux which fallback routine
- 
-

Added Linux which fallback routine

---

README.md

The README file has been updated to clarify that whilst `pwncat` can receive connections from Windows hosts, it requires a Linux host to be run on.

Updated README to clarify host requirements.

---

CHANGELOG.md
docs/source/usage.rst
pwncat/__main__.py
pwncat/commands/connect.py

The `--listen` argument was basically ignored. This happened to work as expected because we used the `--port` argument along with it normally. However, if no `--port` argument was provided, the protocol was not guessed correctly. Using the `--listen` argument is now equivalent to using the explicit `bind://` protocol when connecting.
Also, I corrected the documentation to reflect the correct options for starting a `pwncat` listener.
Fixes #201.
- Correctly set the protocol when using the `--listen` argument.
- Corrected documentation for pwncat listener.

[FIX #201] Correctly handle `--listen` argument and update documentation

---

CHANGELOG.md
README.md
docs/source/installation.rst

Added packaging status and installation instructions for BlackArch linux.
Fixes #178.
- Added packaging status to `README.md`
- Added installation instructions to documentation.

Add installation instructions for BlackArch

---

CHANGELOG.md
pwncat/platform/linux.py

Fixes #208 and #210 Issues.
- Added additional check for stat time of file birth field 
- Removed shell compare with ["nologin", "false", "sync", "git-shell"]
-  Added shell compare with `not in ["bash", "zsh", "ksh", "fish"]`

Issues 208 (stat output verification) and 210 (shell detection) fixes 

---

CHANGELOG.md
pwncat/platform/linux.py

As discussed in #179, the handling of `euid` processes during `Popen` with `shell=True` and during shell detection causes uncaught exceptions or dropped permissions.
In the former case, I simply removed the handling of `shell=True` from `Linux.Popen`. The way that pwncat executes processes without `/bin/sh -c` is equivalent to running with `/bin/sh -c`, so I don't believe this will cause any issues, but needs some more testing before merging.
In the latter case, I simply caught the `OSError` raised by `Path.readlink()` during shell detection. In this case, we fall back to using the `SHELL` environment variable which is unreliable at best. This means that normally, if you are in a `euid` context, you will lose fancy shell highlighting, but this is mainly cosmetic and doing this ensures …

Fix EUID handling in Popen and Shell Detection

---

CHANGELOG.md
docs/requirements.txt
docs/source/commands/index.rst
docs/source/commands/lcd.rst
docs/source/commands/lpwd.rst
pwncat/commands/lcd.py
pwncat/commands/lpwd.py

Added `lpwd` command for printing the current local working directory, and the `lcd` command for changing the current local working directory.
Fixes #218.
- Added `lcd` and `lpwd` commands
- Added relevant documentation.

Added lpwd and lcd commands for local cwd changes

---

CHANGELOG.md
pwncat/__main__.py
pwncat/commands/connect.py

Fixes #225.
-  Fixed parsing of `--ssl` argument in main entrypoint 

Issue 225 ssl parsing

---

CHANGELOG.md
poetry.lock
pwncat/channel/ssh.py
pwncat/facts/__init__.py
pyproject.toml

This PR overhauls the SSH channel implementation to more correctly utilize Paramiko, and also moves our dependency from `paramiko` to `paramiko-ng`, which provides fixes for previously broken parts of `paramiko`.
This not only simplifies the SSH channel implementation, but also means that SSH-Agent should work out of the box and that you can now use keys aside from RSA (tested with an `ed25519` key).
Fixes #91.
- Replaced `paramiko` with `paramiko-ng`
- Utilized Paramiko SSHClient which will also utilize the SSHAgent if available by default and supports key types aside from RSA ([#91](https://github.com/calebstewart/pwncat/issues/91))

Add support for SSHAgent and Key Types outside of RSA

---

CHANGELOG.md
docs/source/persist.rst
poetry.lock
pwncat/modules/agnostic/implant.py
pyproject.toml

Also updated documentation to clarify implant reconnection process.
Fixes #224 .
- Added implant module `list` command to match documentation
- Update documentation to clarify implant reconnection

Added implant module list subcommand

---

.readthedocs.yaml
CHANGELOG.md
docs/requirements.txt
docs/source/conf.py
poetry.lock
pyproject.toml

This is a cosmetic change. I recently found the Furo theme for Sphinx, and really like it. I've changed the theme for the ReadTheDocs documentation to `furo`, and also removed `docs/requirements.txt` in favor of providing the `docs` extra dependency list in `pyproject.toml`.
- Moved documentation theme to [furo](https://github.com/pradyunsg/furo).
- Added Extras group for documentation depenedencies and removed `docs/requirements.txt`.

Update Documentation Theme

---

CHANGELOG.md
pwncat/__main__.py
pwncat/commands/connect.py

This PR fixes #231 which was a bug caused by the previous release that I didn't catch. :frowning_face: 
- Fixed parsing of `--ssl` argument ([#231](https://github.com/calebstewart/pwncat/issues/231)).

Fixed ssl parsing in entrypoint/connect command

---

CHANGELOG.md
pwncat/commands/load.py

The `load` command incorrectly passed the path argument to `Manager.load_modules` as a list instead of expanding to the positional arguments. This fix simply adds the asterisk to expand the list to positional arguments. 
- Fixed `Manger.load_modules` call in `pwncat/commands/load.py`.

Fixed load command path argument

---

CHANGELOG.md
docs/source/conf.py
pwncat/commands/run.py
pwncat/commands/set.py
pwncat/commands/upload.py
pwncat/modules/linux/implant/authorized_key.py
pwncat/platform/linux.py
pwncat/util.py
tests/conftest.py
tests/test_session.py

Fixes #245, it was merely a use of non-str type objects in the `args` list. I have type-casted them with `str(...)`.
There were a few minor issues, as discussed :sweat_smile: in https://github.com/calebstewart/pwncat/discussions/200
- fixed `shlex.join` use with non-str type objects (e.g. `RemotePath`)
- fixed `set` command use with incorrect keys (e.g. `set invalid value`)
- catch missed `PlatformError` for `upload` command
> EDIT: These changes fixes little issues so I am targetting `master`

Fixes #245 and minor patches
